dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.2
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
  - Uniswap/uniswap-v2-core@1.0.1
  - uniswap/v2-periphery@1.0.0-beta.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.2'
      - "@uniswap=Uniswap/uniswap-v2-core@1.0.1"
      - "@uniswap-periphery=uniswap/v2-periphery@1.0.0-beta.0"
    version: 0.8.11
    viaIR: True
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
  dai_address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
  weth_address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  wbtc_address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
networks:
  sepolia2:
    link: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
    vrf_coordinator: "0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625"
    key_hash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"
# settings:
  # gas_limit: "100000000000"
